name: Benchmark
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Run benchmark
        run: go test ./... -benchmem -bench ^Benchmark -benchtime=300000x | tee bench.log

      - name: Check benchmark result
        if: github.event_name == 'pull_request'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: go
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file-path: bench.log
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          alert-comment-cc-users: '@pulsejet'

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        if: github.event_name != 'pull_request'
        with:
          name: Go Benchmark
          tool: go
          output-file-path: bench.log
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          fail-on-alert: true
